### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by varghesep** [Horusiath/AkkaCQRS#9]
While I'm running the application locally, I don't see any response after this line

_child.Forward(command);_

The _sign up_ page returns with a 500 Internal Server Error and simply don't proceed from there.

I noticed that monitoring is integrated with the application. But I don't see any logs in the **Visual Studio output window** neither any logs in the **BIN** or **OBJ** folder.

Could you please let me know if I have to install any special software like [Kamon and Stasd](http://www.typesafe.com/activator/template/akka-monitoring-kamon-statsd) to see the logs?

![akkacqrslog](https://cloud.githubusercontent.com/assets/12233474/8511875/327c1dbe-22ee-11e5-996a-c7abaab08e26.PNG)

I updated the HOCON to the following. I still don't see any logs in the output window:

```
  <akka>
    <hocon>
      <![CDATA[
        akka {
          loglevel = DEBUG
          loggers = [ "Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog" ]
          actor {
            autoreceive = on
            lifecycle = on
            fsm = on
          }
        }
      ]]>
    </hocon>
  </akka>
```

**Comment by Horusiath** [comment]
Yes, this example should cooperate with StatsD, but your issue seems to have a different reason. I'll check it out later.

**Comment by varghesep** [comment]
I made a change in the code to dump the log to a txt file as below:

```
        private void ConfigureLogger(IAppBuilder app)
        {
            var logger = new LoggerConfiguration().WriteTo.File(@"c:\temp\log.txt").CreateLogger();
            Serilog.Debugging.SelfLog.Out = Console.Out;
            Serilog.Log.Logger = logger;
        }
```

This is what I see in the log.txt

```
2015-07-07 20:39:27.726 -05:00 [Error] "Access to the path 'snapshots' is denied."
[akka://akka-cqrs/system/akka.persistence.snapshot-store.local]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.UnauthorizedAccessException: Access to the path 'snapshots' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.DirectoryInfo.Create()
   at Akka.Persistence.Snapshot.LocalSnapshotStore.PreStart()
   at Akka.Actor.ActorBase.AroundPreStart()
   at Akka.Actor.ActorCell.<>c__DisplayClass4c.<Create>b__4b()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SystemInvoke(Envelope envelope)
2015-07-07 20:39:27.773 -05:00 [Information] "Message LoadSnapshot from akka://akka-cqrs/user/users/user-ec81a30f12d94f9bb0157e2b0e9746f7 to akka://akka-cqrs/system/akka.persistence.snapshot-store.local was not delivered. 1 dead letters encountered."
```

Is this caused by the directory **snapshot** not existing? I'm an admin on this laptop and I was able to see another example was able to create a **snapshot** folder under the **bin** folder.

**Comment by Horusiath** [comment]
Your web app may be running using different permissions than your own, i.e. when your running your app on IIS.

**Comment by 4deeptech** [comment]
The snapshot setup by default uses the local snapshot store implementation. It configures by looking for a hocon default property for 'dir' which is relative.  In this case it is probably the root folder for IISEXPRESS which for me is:  C:\Program Files (x86)\IIS Express.  To get anywhere, I had to run VStudio as administrator to track this down. Other option is to use hocon and configure an alternate snapshot store.  Even after doing this I haven't gotten everything to work right.  I can create the j doe user and it displays a picture and generic content. I click create account and it creates an account. If I go to sign in and enter the jdoe email and pass it just hangs on the ask. Of course that may be that sign in once you are signed in may get ignored.  Trying to figure out what all should work and what I should see and be able to do in the UI.
